name: Tests

on:
  push:
    branches:
      - master
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  runs-on: ${{ matrix.os }}
  test:
    strategy:
      matrix:
        os: ["macos-latest", "windows-latest", "ubuntu-latest"]
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 8
      - name: Setup bnd
        id: bnd
        uses: ./
        with:
          version: 1
      - name: Test it
        run: bnd version
